/**
 * Service worker, written after the build.
 *
 *   node scripts/make-sw.mjs
 *
 * Vite hashes every asset filename, so the precache list can only be known
 * once `dist/` exists. Generating the worker here means the installed app has
 * the complete file list from its very first launch - which matters, because
 * the whole point of putting this on a home screen is that it starts on a
 * train with no signal.
 *
 * The cache name carries a hash of that list, so a deploy that changes one
 * byte retires the old cache and nothing has to be invalidated by hand.
 */
import { createHash } from 'node:crypto';
import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative, resolve } from 'node:path';

const DIST = resolve(dirname(fileURLToPath(import.meta.url)), '../dist');

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

const files = walk(DIST)
  .map((f) => relative(DIST, f).split('\\').join('/'))
  // Source maps are for developers and are megabytes; the worker is for
  // players on a train.
  .filter((f) => !f.endsWith('.map') && f !== 'sw.js')
  .sort();

const version = createHash('sha256').update(files.join('\n')).digest('hex').slice(0, 12);
const precache = ['./', ...files.map((f) => `./${f}`)];

const sw = `/* Generated by scripts/make-sw.mjs - do not edit. */
const CACHE = 'scrap-empire-${version}';
const PRECACHE = ${JSON.stringify(precache, null, 2)};

self.addEventListener('install', (event) => {
  // Cache everything up front so the first offline launch works, then take
  // over immediately - a player who just installed should not have to close
  // the app once before it works.
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Navigations: try the network first so a new deploy is picked up on the
  // next online launch, fall back to the cached shell when there is no signal.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put(request, copy));
          return response;
        })
        .catch(() => caches.match(request).then((hit) => hit || caches.match('./'))),
    );
    return;
  }

  // Everything else is content-hashed, so a cache hit is always correct.
  event.respondWith(
    caches.match(request).then(
      (hit) =>
        hit ||
        fetch(request).then((response) => {
          if (response.ok && response.type === 'basic') {
            const copy = response.clone();
            caches.open(CACHE).then((cache) => cache.put(request, copy));
          }
          return response;
        }),
    ),
  );
});
`;

writeFileSync(resolve(DIST, 'sw.js'), sw);
console.log(`sw.js  ${files.length} Dateien vorgeladen  ·  Cache scrap-empire-${version}`);
